### PR TITLE
Suggestions, review, and general advice

### PR DESCRIPTION
**Pull request by TheChymera**

### CODE REVIEW

**Comment by TheChymera** [comment]
A few more general comments:

* “machinetype” hints at an actual machine, and thus evokes the architecture. Why not “systemtype”?
* Referring to both the BuildServer and the BuildServer directory on the BuildServer as BuildServer makes things a bit confusing - especially in the flowcharts. You should disambiguate these names.

**Comment by Doeme** [comment]
About the machinetype thing: It's called that way in the BuildServer scripts, and I won't change that now and risk breakage.

The BuildServer ambiguity is unfortunate. I'll try to make it clearer

**Comment by TheChymera** [comment]
I'll send you all I've got shortly before 23:00, that should give you about an hour to resolve all !!!'s and add your finishing Doemish touches ;)

**Comment by TheChymera** [comment]
I think content-wise you've adequately covered most of the project, I would concentrate on proofreading and updating your tone. The imperatives under “future work” need updating, and colloquialisms such as software pulling other software need to be replaced with more appropriate formulations. NBot least of all, check your pronoun usage. You often use a third person pronoun as a subject, and it seems you're refering to the general idea, rather than to a specific aforementioned word.

> The conflict is then carried out in the dynamic
loader (ld.so). It traverses the dependency tree and first loads the functions (symbols) from B1 to
satisfy the dependencies of D1

What is it? The conflict? It's less awkward to repeat a word in the next sentence, than to have an unclear pronoun (though it is preferable to eschew both cases).

**Comment by Doeme** [comment]
Do you want to be an author of the document?

**Comment by TheChymera** [comment]
Not on this document, my contributions were intended purely as advice and suggestions, but you should list me, along Markus Rudin as your adviser.

**Comment by Doeme** [comment]
Where should I list you and markus?

**Comment by TheChymera** [comment]
Bottom-right corner of the title page, under a line saying “Advisers:” you should list us in alphabetical order, and specify the Prof. Dr. titles for Markus. On the hird line list the institution we both belong to (Institute for Biomedical Engineering, D-ITET, ETH Zürich)

**Pull request closed without merging**
